bridge net support; remove ubuntu 16 support

diff --git a/scripts/vmnet b/scripts/vmnet
--- a/scripts/vmnet
+++ b/scripts/vmnet
@@ -2,19 +2,19 @@
 # /usr/local/bin/vmnet
 # Set up network and hostname. See https://github.com/lencap/vm
 
-renameNIC () {
-    echo "==> Renaming NIC [$1] to [$2]"
-    ip link set $1 down && ip link set $1 name $2 && ip link set $2 up
-}
-
 osDist=$(hostnamectl | awk '/Operating System/ {print $3}' | tr 'A-Z' 'a-z')
 vmName=$(sudo VBoxControl guestproperty get '/vm/name' | awk '/^Value/ {print $2}')
 vmIP=$(sudo VBoxControl guestproperty get '/vm/ip' | awk '/^Value/ {print $2}')
+netType=$(sudo VBoxControl guestproperty get '/vm/nettype' | awk '/^Value/ {print $2}')
+[[ "$netType" != "bri" ]] && netType="ho"   # Default to HostOnly no matter what
 echo "==> OS        = [$osDist]"
 echo "==> Hostname  = [$vmName]"
 echo "==> IPAddress = [$vmIP]"
+echo "==> NetType   = [$netType]"
 [[ -z "$vmName" ]] && echo "VBoxControl guestproperty get '/vm/name' is empty." && exit 1
 [[ -z "$vmIP" ]] && echo "VBoxControl guestproperty get '/vm/ip' is empty." && exit 1
+
+gateWay=${vmIP%.*}.1   # For Bridge networking, we'll assume 1st IP is both gateway and DNS
 
 if [[ "$osDist" == "centos" ]]; then
     echo "==> Configuring CentOS network"
@@ -22,49 +22,73 @@ if [[ "$osDist" == "centos" ]]; then
     sudo systemctl disable NetworkManager
     sudo systemctl stop network
     for n in $(ip l | awk '/^[0-9]/ {print $2}') ; do
-        [[ "$n" == "eth0:" ]] && renameNIC eth0 enp0s3
-        [[ "$n" == "eth1:" ]] && renameNIC eth1 enp0s8
+        if [[ "$n" == "eth0:" ]]; then
+            ip link set eth0 down && ip link set eth0 name enp0s3  # Force new name
+            sudo rm -f /etc/sysconfig/network-scripts/ifcfg-eth0   # Cleanup
+        fi
+        if [[ "$n" == "eth1:" ]]; then
+            ip link set eth1 down && ip link set eth1 name enp0s8
+            sudo rm -f /etc/sysconfig/network-scripts/ifcfg-eth1
+        fi
     done
     nic0=enp0s3 ; nic1=enp0s8
     nic0File=/etc/sysconfig/network-scripts/ifcfg-$nic0
     nic1File=/etc/sysconfig/network-scripts/ifcfg-$nic1
-    echo "==> VirtualBox Adapter 1 [NAT]: Configuring $nic0 as DHCP client"
-    # DHCP should have already configured NIC0
-    echo "DEVICE=\"$nic0\"" > $nic0File
-    echo "BOOTPROTO=\"dhcp\"" >> $nic0File
-    echo "ONBOOT=\"yes\"" >> $nic0File
-    echo "NM_CONTROLLED=\"no\"" >> $nic0File
-    MAC=$(cat /sys/class/net/$nic0/address)
-    echo "HWADDR=\"$MAC\"" >> $nic0File
-    echo "==> VirtualBox Adapter 2 [HostOnly]: Configuring $nic1 with static IP $vmIP"
-    echo "DEVICE=\"$nic1\"" > $nic1File
-    echo "BOOTPROTO=\"static\"" >> $nic1File
-    echo "ONBOOT=\"yes\"" >> $nic1File
-    echo "NM_CONTROLLED=\"no\"" >> $nic1File
-    echo "IPADDR=\"$vmIP\"" >> $nic1File
-    echo "NETMASK=\"255.255.255.0\"" >> $nic1File
-    MAC=$(cat /sys/class/net/$nic1/address)
-    echo "HWADDR=\"$MAC\"" >> $nic1File
+    if [[ "$netType" == "bri" ]]; then
+        echo "==> Configuring $nic0 as DISABLED, and $nic1 with static IP $vmIP in Bridged mode"
+        ip link set $nic0 down
+        sudo rm -f $nic0File
+
+        echo "DEVICE=\"$nic1\"" > $nic1File
+        echo "BOOTPROTO=\"static\"" >> $nic1File
+        echo "ONBOOT=\"yes\"" >> $nic1File
+        echo "NM_CONTROLLED=\"no\"" >> $nic1File
+        echo "IPADDR=\"$vmIP\"" >> $nic1File
+        echo "NETMASK=\"255.255.255.0\"" >> $nic1File
+        MAC=$(cat /sys/class/net/$nic1/address)
+        echo "HWADDR=\"$MAC\"" >> $nic1File
+        echo "GATEWAY=\"$gateWay\"" >> $nic1File
+        echo "DNS1=\"$gateWay\"" >> $nic1File
+    else
+        echo "==> Configuring $nic0 as DHCP client, and $nic1 with static IP $vmIP in HostOnly mode"
+        # DHCP should have already configured NIC0
+        echo "DEVICE=\"$nic0\"" > $nic0File
+        echo "BOOTPROTO=\"dhcp\"" >> $nic0File
+        echo "ONBOOT=\"yes\"" >> $nic0File
+        echo "NM_CONTROLLED=\"no\"" >> $nic0File
+        MAC=$(cat /sys/class/net/$nic0/address)
+        echo "HWADDR=\"$MAC\"" >> $nic0File
+
+        echo "DEVICE=\"$nic1\"" > $nic1File
+        echo "BOOTPROTO=\"static\"" >> $nic1File
+        echo "ONBOOT=\"yes\"" >> $nic1File
+        echo "NM_CONTROLLED=\"no\"" >> $nic1File
+        echo "IPADDR=\"$vmIP\"" >> $nic1File
+        echo "NETMASK=\"255.255.255.0\"" >> $nic1File
+        MAC=$(cat /sys/class/net/$nic1/address)
+        echo "HWADDR=\"$MAC\"" >> $nic1File
+    fi
     sudo systemctl start network
 elif [[ "$osDist" == "ubuntu" ]]; then
     echo "==> Configuring Ubuntu network"
     nic0=enp0s3 ; nic1=enp0s8
-    echo "==> VirtualBox Adapter 1 [NAT]: Configuring $nic0 as DHCP client"
-    echo "==> VirtualBox Adapter 2 [HostOnly]: Configuring $nic1 with static IP $vmIP"
     osRel=$(hostnamectl | awk '/Operating System/ {print $4}') ; osRel=${osRel%%.*}
-    if [[ "$osRel" == "16" ]]; then            # Ubuntu 16.04
-        sudo systemctl stop networking
-        nic0File=/etc/network/interfaces
-        # DHCP should have already configured NIC0
-        nic1File=/etc/network/interfaces.d/20-${nic1}.cfg
-        echo "auto $nic1" > $nic1File
-        echo "iface $nic1 inet static" >> $nic1File
-        echo "address $vmIP" >> $nic1File
-        echo "netmask 255.255.255.0" >> $nic1File
-        sudo systemctl start networking
-    else                                       # Newer Ubuntu use netplan
-        sudo systemctl stop systemd-networkd
-        cfg=/etc/netplan/01-netcfg.yaml
+    [[ "$osRel" == "16" ]] && echo "FATAL: Ubuntu v16 is not supported. Only v18 and above." && exit 1
+    sudo systemctl stop systemd-networkd
+    cfg=/etc/netplan/01-netcfg.yaml
+    if [[ "$netType" == "bri" ]]; then
+        echo "==> Configuring $nic0 as DISABLED, and $nic1 with static IP $vmIP in Bridged mode"
+        sudo echo "network:" > $cfg
+        sudo echo "  version: 2" >> $cfg
+        sudo echo "  renderer: networkd" >> $cfg
+        sudo echo "  ethernets:" >> $cfg
+        sudo echo "    $nic1:" >> $cfg
+        sudo echo "      addresses: [$vmIP/24]" >> $cfg
+        sudo echo "      gateway4: $gateWay" >> $cfg
+        sudo echo "      nameservers:" >> $cfg
+        sudo echo "        addresses: [$gateWay]" >> $cfg
+    else
+        echo "==> Configuring $nic0 as DHCP client, and $nic1 with static IP $vmIP in HostOnly mode"
         sudo echo "network:" > $cfg
         sudo echo "  version: 2" >> $cfg
         sudo echo "  renderer: networkd" >> $cfg
@@ -73,11 +97,11 @@ elif [[ "$osDist" == "ubuntu" ]]; then
         sudo echo "      dhcp4: yes" >> $cfg
         sudo echo "    $nic1:" >> $cfg
         sudo echo "      addresses: [$vmIP/24]" >> $cfg
-        sudo systemctl start systemd-networkd
-        sudo netplan apply
     fi
+    sudo systemctl start systemd-networkd
+    sudo netplan apply
 else
-    echo "==> Unsupported OS. Giving up on network and hostname setup."
+    echo "==> Unsupported OS. Giving up on network and hostname set up."
     exit 1
 fi
 
